In [5]:
import pandas as pd

In [6]:
train=pd.read_csv('train.csv')

In [7]:
train

,patient_id,patient_race,payer_type,patient_state,patient_zip3,Region,Division,patient_age,patient_gender,bmi,...,Average of Apr-18,Average of May-18,Average of Jun-18,Average of Jul-18,Average of Aug-18,Average of Sep-18,Average of Oct-18,Average of Nov-18,Average of Dec-18,metastatic_diagnosis_period
0,268700,NaN,COMMERCIAL,AR,724,South,West South Central,39,F,NaN,...,52.55,74.77,79.96,81.69,78.30,74.56,59.98,42.98,41.18,191
1,484983,White,NaN,IL,629,Midwest,East North Central,55,F,35.36,...,49.30,72.87,77.40,77.43,75.83,72.64,58.36,39.68,39.71,33
2,277055,NaN,COMMERCIAL,CA,925,West,Pacific,59,F,NaN,...,68.50,70.31,78.61,87.24,85.52,80.75,70.81,62.67,55.58,157
3,320055,Hispanic,MEDICAID,CA,900,West,Pacific,59,F,NaN,...,63.34,63.10,67.45,75.86,75.24,71.10,68.95,65.46,59.46,146
4,190386,NaN,COMMERCIAL,CA,934,West,Pacific,71,F,NaN,...,59.45,60.24,64.77,69.81,70.13,68.10,65.38,60.72,54.08,286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13168,588544,Hispanic,MEDICAID,PA,191,Northeast,Middle Atlantic,59,F,NaN,...,48.81,66.12,70.38,77.18,77.53,70.90,56.53,41.46,37.49,106
13169,393047,NaN,COMMERCIAL,TX,757,South,West South Central,73,F,30.67,...,62.03,77.82,84.52,85.35,84.61,78.50,67.24,52.16,50.01,92
13170,790904,NaN,COMMERCIAL,CA,928,West,Pacific,19,F,NaN,...,66.20,66.04,70.87,80.68,79.75,75.27,71.40,66.01,59.20,0
13171,455518,NaN,COMMERCIAL,MI,481,Midwest,East North Central,52,F,NaN,...,39.93,63.56,68.68,72.13,72.55,66.17,49.79,34.16,32.28,330
13172,379418,Hispanic,MEDICAID,CA,900,West,Pacific,63,F,NaN,...,63.34,63.10,67.45,75.86,75.24,71.10,68.95,65.46,59.46,0

In [8]:
import pandas as pd
import numpy as np

# Assuming your dataset is named 'train'

# Step 1: Group data by ZIP code and age group
age_groups = pd.cut(train['patient_age'], bins=range(0, 120, 10), right=False)
grouped = train.groupby(['patient_zip3', age_groups])

# Step 2: Calculate average BMI for valid groups
avg_bmi_by_group = {}
for group, group_data in grouped:
    non_null_bmi = group_data['bmi'].dropna()
    if not non_null_bmi.empty and non_null_bmi.count() > 1:  # Ensure there are enough non-null values
        avg_bmi_by_group[group] = non_null_bmi.mean()
    else:
        avg_bmi_by_group[group] = np.nan  # Set NaN if there are not enough non-null values

# Step 3: Replace null BMI values with corresponding averages
for index, row in train.iterrows():
    if pd.isnull(row['bmi']):
        zip_code = row['patient_zip3']
        age_group = pd.cut([row['patient_age']], bins=range(0, 120, 10), right=False)[0]
        if (zip_code, age_group) in avg_bmi_by_group and not pd.isnull(avg_bmi_by_group[(zip_code, age_group)]):
            train.at[index, 'bmi'] = avg_bmi_by_group[(zip_code, age_group)]
        else:
            # Replace NaN BMI values with a default value, or you can choose to skip them
            train.at[index, 'bmi'] = 29.168808   # Replace with a default value

# Now, train dataset should have null BMI values replaced with corresponding averages or default values

In [9]:
train

,patient_id,patient_race,payer_type,patient_state,patient_zip3,Region,Division,patient_age,patient_gender,bmi,...,Average of Apr-18,Average of May-18,Average of Jun-18,Average of Jul-18,Average of Aug-18,Average of Sep-18,Average of Oct-18,Average of Nov-18,Average of Dec-18,metastatic_diagnosis_period
0,268700,NaN,COMMERCIAL,AR,724,South,West South Central,39,F,29.168808,...,52.55,74.77,79.96,81.69,78.30,74.56,59.98,42.98,41.18,191
1,484983,White,NaN,IL,629,Midwest,East North Central,55,F,35.360000,...,49.30,72.87,77.40,77.43,75.83,72.64,58.36,39.68,39.71,33
2,277055,NaN,COMMERCIAL,CA,925,West,Pacific,59,F,30.509167,...,68.50,70.31,78.61,87.24,85.52,80.75,70.81,62.67,55.58,157
3,320055,Hispanic,MEDICAID,CA,900,West,Pacific,59,F,30.127778,...,63.34,63.10,67.45,75.86,75.24,71.10,68.95,65.46,59.46,146
4,190386,NaN,COMMERCIAL,CA,934,West,Pacific,71,F,29.168808,...,59.45,60.24,64.77,69.81,70.13,68.10,65.38,60.72,54.08,286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13168,588544,Hispanic,MEDICAID,PA,191,Northeast,Middle Atlantic,59,F,30.226667,...,48.81,66.12,70.38,77.18,77.53,70.90,56.53,41.46,37.49,106
13169,393047,NaN,COMMERCIAL,TX,757,South,West South Central,73,F,30.670000,...,62.03,77.82,84.52,85.35,84.61,78.50,67.24,52.16,50.01,92
13170,790904,NaN,COMMERCIAL,CA,928,West,Pacific,19,F,29.168808,...,66.20,66.04,70.87,80.68,79.75,75.27,71.40,66.01,59.20,0
13171,455518,NaN,COMMERCIAL,MI,481,Midwest,East North Central,52,F,30.047857,...,39.93,63.56,68.68,72.13,72.55,66.17,49.79,34.16,32.28,330
13172,379418,Hispanic,MEDICAID,CA,900,West,Pacific,63,F,28.945000,...,63.34,63.10,67.45,75.86,75.24,71.10,68.95,65.46,59.46,0

In [10]:
import numpy as np

# Define a function to determine patient_race based on race percentages
def determine_patient_race(row):
    # Check if patient_race is null
    if pd.isnull(row['patient_race']):
        # Check race percentages
        if row['race_black'] > 30:
            return 'Black'
        elif row['race_asian'] > 25:
            return 'Asian'
        elif row['race_other'] > 30:
            return 'Other'
        elif row['race_white'] > 80:
            return 'White'
        else:
            return 'White'  # Default to White if none of the conditions are met
    else:
        return row['patient_race']  # Return existing patient_race if not null

# Apply the function to each row where patient_race is null
train['patient_race'] = train.apply(lambda row: determine_patient_race(row), axis=1)

In [11]:
train

,patient_id,patient_race,payer_type,patient_state,patient_zip3,Region,Division,patient_age,patient_gender,bmi,...,Average of Apr-18,Average of May-18,Average of Jun-18,Average of Jul-18,Average of Aug-18,Average of Sep-18,Average of Oct-18,Average of Nov-18,Average of Dec-18,metastatic_diagnosis_period
0,268700,White,COMMERCIAL,AR,724,South,West South Central,39,F,29.168808,...,52.55,74.77,79.96,81.69,78.30,74.56,59.98,42.98,41.18,191
1,484983,White,NaN,IL,629,Midwest,East North Central,55,F,35.360000,...,49.30,72.87,77.40,77.43,75.83,72.64,58.36,39.68,39.71,33
2,277055,White,COMMERCIAL,CA,925,West,Pacific,59,F,30.509167,...,68.50,70.31,78.61,87.24,85.52,80.75,70.81,62.67,55.58,157
3,320055,Hispanic,MEDICAID,CA,900,West,Pacific,59,F,30.127778,...,63.34,63.10,67.45,75.86,75.24,71.10,68.95,65.46,59.46,146
4,190386,White,COMMERCIAL,CA,934,West,Pacific,71,F,29.168808,...,59.45,60.24,64.77,69.81,70.13,68.10,65.38,60.72,54.08,286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13168,588544,Hispanic,MEDICAID,PA,191,Northeast,Middle Atlantic,59,F,30.226667,...,48.81,66.12,70.38,77.18,77.53,70.90,56.53,41.46,37.49,106
13169,393047,White,COMMERCIAL,TX,757,South,West South Central,73,F,30.670000,...,62.03,77.82,84.52,85.35,84.61,78.50,67.24,52.16,50.01,92
13170,790904,White,COMMERCIAL,CA,928,West,Pacific,19,F,29.168808,...,66.20,66.04,70.87,80.68,79.75,75.27,71.40,66.01,59.20,0
13171,455518,White,COMMERCIAL,MI,481,Midwest,East North Central,52,F,30.047857,...,39.93,63.56,68.68,72.13,72.55,66.17,49.79,34.16,32.28,330
13172,379418,Hispanic,MEDICAID,CA,900,West,Pacific,63,F,28.945000,...,63.34,63.10,67.45,75.86,75.24,71.10,68.95,65.46,59.46,0

In [12]:
# Define a function to determine payer_type based on conditions
def determine_payer_type(row):
    if pd.isnull(row['payer_type']):
        if row['patient_age'] >= 65:
            return 'MEDICARE ADVANTAGE'
        elif row['income_individual_median'] < 31255:
            return 'MEDICAID'
        elif row['income_individual_median'] > 36000 and 45 < row['patient_age'] < 65:
            return 'COMMERCIAL'
        else:
            return 'COMMERCIAL'
    else:
        return row['payer_type']  # Return existing payer_type if not null

# Apply the function to each row where payer_type is null
train['payer_type'] = train.apply(lambda row: determine_payer_type(row), axis=1)

In [13]:
train

,patient_id,patient_race,payer_type,patient_state,patient_zip3,Region,Division,patient_age,patient_gender,bmi,...,Average of Apr-18,Average of May-18,Average of Jun-18,Average of Jul-18,Average of Aug-18,Average of Sep-18,Average of Oct-18,Average of Nov-18,Average of Dec-18,metastatic_diagnosis_period
0,268700,White,COMMERCIAL,AR,724,South,West South Central,39,F,29.168808,...,52.55,74.77,79.96,81.69,78.30,74.56,59.98,42.98,41.18,191
1,484983,White,MEDICAID,IL,629,Midwest,East North Central,55,F,35.360000,...,49.30,72.87,77.40,77.43,75.83,72.64,58.36,39.68,39.71,33
2,277055,White,COMMERCIAL,CA,925,West,Pacific,59,F,30.509167,...,68.50,70.31,78.61,87.24,85.52,80.75,70.81,62.67,55.58,157
3,320055,Hispanic,MEDICAID,CA,900,West,Pacific,59,F,30.127778,...,63.34,63.10,67.45,75.86,75.24,71.10,68.95,65.46,59.46,146
4,190386,White,COMMERCIAL,CA,934,West,Pacific,71,F,29.168808,...,59.45,60.24,64.77,69.81,70.13,68.10,65.38,60.72,54.08,286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13168,588544,Hispanic,MEDICAID,PA,191,Northeast,Middle Atlantic,59,F,30.226667,...,48.81,66.12,70.38,77.18,77.53,70.90,56.53,41.46,37.49,106
13169,393047,White,COMMERCIAL,TX,757,South,West South Central,73,F,30.670000,...,62.03,77.82,84.52,85.35,84.61,78.50,67.24,52.16,50.01,92
13170,790904,White,COMMERCIAL,CA,928,West,Pacific,19,F,29.168808,...,66.20,66.04,70.87,80.68,79.75,75.27,71.40,66.01,59.20,0
13171,455518,White,COMMERCIAL,MI,481,Midwest,East North Central,52,F,30.047857,...,39.93,63.56,68.68,72.13,72.55,66.17,49.79,34.16,32.28,330
13172,379418,Hispanic,MEDICAID,CA,900,West,Pacific,63,F,28.945000,...,63.34,63.10,67.45,75.86,75.24,71.10,68.95,65.46,59.46,0

In [14]:
pd.set_option('display.max_rows', None) 
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)
print("\nMissing values in each column:")
print(train.isnull().sum())

Missing values in each column:
patient_id                                   0
patient_race                                 0
payer_type                                   0
patient_state                                0
patient_zip3                                 0
Region                                       0
Division                                     0
patient_age                                  0
patient_gender                               0
bmi                                          0
breast_cancer_diagnosis_code                 0
breast_cancer_diagnosis_desc                 0
metastatic_cancer_diagnosis_code             0
metastatic_first_novel_treatment         13162
metastatic_first_novel_treatment_type    13162
population                                   0
density                                      0
age_median                                   0
age_under_10                                 0
age_10_to_19                                 0
age_20s                                      0
age_30s                                      0
age_40s                                      0
age_50s                                      0
age_60s                                      0
age_70s                                      0
age_over_80                                  0
male                                         0
female                                       0
married                                      0
divorced                                     0
never_married                                0
widowed                                      0
family_size                                  5
family_dual_income                           5
income_household_median                      5
income_household_under_5                     5
income_household_5_to_10                     5
income_household_10_to_15                    5
income_household_15_to_20                    5
income_household_20_to_25                    5
income_household_25_to_35                    5
income_household_35_to_50                    5
income_household_50_to_75                    5
income_household_75_to_100                   5
income_household_100_to_150                  5
income_household_150_over                    5
income_household_six_figure                  5
income_individual_median                     0
home_ownership                               5
housing_units                                0
home_value                                   5
rent_median                                  5
rent_burden                                  5
education_less_highschool                    0
education_highschool                         0
education_some_college                       0
education_bachelors                          0
education_graduate                           0
education_college_or_above                   0
education_stem_degree                        0
labor_force_participation                    0
unemployment_rate                            0
self_employed                                5
farmer                                       5
race_white                                   0
race_black                                   0
race_asian                                   0
race_native                                  0
race_pacific                                 0
race_other                                   0
race_multiple                                0
hispanic                                     0
disabled                                     0
poverty                                      5
limited_english                              5
commute_time                                 0
health_uninsured                             0
veteran                                      0
Average of Jan-13                           33
Average of Feb-13                            3
Average of Mar-13                            0
Average of Apr-13                            0
Average of May-13                            3
Average of Jun-13                           20
Average of Jul-13                            0
Average of Aug-13                           17
Average of Sep-13                           27
Average of Oct-13                           59
Average of Nov-13                            3
Average of Dec-13                            3
Average of Jan-14                            4
Average of Feb-14                            9
Average of Mar-14                           29
Average of Apr-14                          180
Average of May-14                            0
Average of Jun-14                          152
Average of Jul-14                            0
Average of Aug-14                            0
Average of Sep-14                            0
Average of Oct-14                            0
Average of Nov-14                           24
Average of Dec-14                            0
Average of Jan-15                            6
Average of Feb-15                           12
Average of Mar-15                           12
Average of Apr-15                           28
Average of May-15                            0
Average of Jun-15                            0
Average of Jul-15                            0
Average of Aug-15                           22
Average of Sep-15                            0
Average of Oct-15                           16
Average of Nov-15                           16
Average of Dec-15                           18
Average of Jan-16                           16
Average of Feb-16                           16
Average of Mar-16                            0
Average of Apr-16                            0
Average of May-16                           19
Average of Jun-16                            0
Average of Jul-16                           16
Average of Aug-16                            0
Average of Sep-16                            0
Average of Oct-16                            0
Average of Nov-16                            3
Average of Dec-16                           13
Average of Jan-17                            9
Average of Feb-17                            0
Average of Mar-17                            0
Average of Apr-17                            0
Average of May-17                            0
Average of Jun-17                            1
Average of Jul-17                           31
Average of Aug-17                            0
Average of Sep-17                           10
Average of Oct-17                           21
Average of Nov-17                            5
Average of Dec-17                            0
Average of Jan-18                            0
Average of Feb-18                            5
Average of Mar-18                            6
Average of Apr-18                            0
Average of May-18                            0
Average of Jun-18                            9
Average of Jul-18                           46
Average of Aug-18                           16
Average of Sep-18                            7
Average of Oct-18                            7
Average of Nov-18                           12
Average of Dec-18                           33
metastatic_diagnosis_period                  0
dtype: int64

In [15]:
# Drop the specified columns
train.drop(['metastatic_first_novel_treatment', 'metastatic_first_novel_treatment_type'], axis=1, inplace=True)

In [16]:
print(train.isnull().sum())

patient_id                            0
patient_race                          0
payer_type                            0
patient_state                         0
patient_zip3                          0
Region                                0
Division                              0
patient_age                           0
patient_gender                        0
bmi                                   0
breast_cancer_diagnosis_code          0
breast_cancer_diagnosis_desc          0
metastatic_cancer_diagnosis_code      0
population                            0
density                               0
age_median                            0
age_under_10                          0
age_10_to_19                          0
age_20s                               0
age_30s                               0
age_40s                               0
age_50s                               0
age_60s                               0
age_70s                               0
age_over_80                           0
male                                  0
female                                0
married                               0
divorced                              0
never_married                         0
widowed                               0
family_size                           5
family_dual_income                    5
income_household_median               5
income_household_under_5              5
income_household_5_to_10              5
income_household_10_to_15             5
income_household_15_to_20             5
income_household_20_to_25             5
income_household_25_to_35             5
income_household_35_to_50             5
income_household_50_to_75             5
income_household_75_to_100            5
income_household_100_to_150           5
income_household_150_over             5
income_household_six_figure           5
income_individual_median              0
home_ownership                        5
housing_units                         0
home_value                            5
rent_median                           5
rent_burden                           5
education_less_highschool             0
education_highschool                  0
education_some_college                0
education_bachelors                   0
education_graduate                    0
education_college_or_above            0
education_stem_degree                 0
labor_force_participation             0
unemployment_rate                     0
self_employed                         5
farmer                                5
race_white                            0
race_black                            0
race_asian                            0
race_native                           0
race_pacific                          0
race_other                            0
race_multiple                         0
hispanic                              0
disabled                              0
poverty                               5
limited_english                       5
commute_time                          0
health_uninsured                      0
veteran                               0
Average of Jan-13                    33
Average of Feb-13                     3
Average of Mar-13                     0
Average of Apr-13                     0
Average of May-13                     3
Average of Jun-13                    20
Average of Jul-13                     0
Average of Aug-13                    17
Average of Sep-13                    27
Average of Oct-13                    59
Average of Nov-13                     3
Average of Dec-13                     3
Average of Jan-14                     4
Average of Feb-14                     9
Average of Mar-14                    29
Average of Apr-14                   180
Average of May-14                     0
Average of Jun-14                   152
Average of Jul-14                     0
Average of Aug-14                     0
Average of Sep-14                     0
Average of Oct-14                     0
Average of Nov-14                    24
Average of Dec-14                     0
Average of Jan-15                     6
Average of Feb-15                    12
Average of Mar-15                    12
Average of Apr-15                    28
Average of May-15                     0
Average of Jun-15                     0
Average of Jul-15                     0
Average of Aug-15                    22
Average of Sep-15                     0
Average of Oct-15                    16
Average of Nov-15                    16
Average of Dec-15                    18
Average of Jan-16                    16
Average of Feb-16                    16
Average of Mar-16                     0
Average of Apr-16                     0
Average of May-16                    19
Average of Jun-16                     0
Average of Jul-16                    16
Average of Aug-16                     0
Average of Sep-16                     0
Average of Oct-16                     0
Average of Nov-16                     3
Average of Dec-16                    13
Average of Jan-17                     9
Average of Feb-17                     0
Average of Mar-17                     0
Average of Apr-17                     0
Average of May-17                     0
Average of Jun-17                     1
Average of Jul-17                    31
Average of Aug-17                     0
Average of Sep-17                    10
Average of Oct-17                    21
Average of Nov-17                     5
Average of Dec-17                     0
Average of Jan-18                     0
Average of Feb-18                     5
Average of Mar-18                     6
Average of Apr-18                     0
Average of May-18                     0
Average of Jun-18                     9
Average of Jul-18                    46
Average of Aug-18                    16
Average of Sep-18                     7
Average of Oct-18                     7
Average of Nov-18                    12
Average of Dec-18                    33
metastatic_diagnosis_period           0
dtype: int64

In [17]:
columns_to_fill = [
    'family_size', 'family_dual_income', 'income_household_median', 'income_household_under_5',
    'income_household_5_to_10', 'income_household_10_to_15', 'income_household_15_to_20',
    'income_household_20_to_25', 'income_household_25_to_35', 'income_household_35_to_50',
    'income_household_50_to_75', 'income_household_75_to_100', 'income_household_100_to_150',
    'income_household_150_over', 'income_household_six_figure', 'home_ownership', 'home_value',
    'rent_median', 'rent_burden', 'poverty', 'limited_english', 'Average of Jan-13', 'Average of Feb-13',
    'Average of May-13', 'Average of Jun-13', 'Average of Aug-13', 'Average of Sep-13', 'Average of Oct-13',
    'Average of Nov-13', 'Average of Dec-13', 'Average of Jan-14', 'Average of Feb-14', 'Average of Mar-14',
    'Average of Apr-14', 'Average of May-14', 'Average of Jun-14', 'Average of Nov-14', 'Average of Jan-15',
    'Average of Feb-15', 'Average of Mar-15', 'Average of Apr-15', 'Average of Aug-15', 'Average of Oct-15',
    'Average of Nov-15', 'Average of Dec-15', 'Average of Jan-16', 'Average of Feb-16', 'Average of May-16',
    'Average of Jul-16', 'Average of Nov-16', 'Average of Dec-16', 'Average of Jan-17', 'Average of Jun-17',
    'Average of Jul-17', 'Average of Sep-17', 'Average of Oct-17', 'Average of Nov-17', 'Average of Feb-18',
    'Average of Mar-18', 'Average of Jun-18', 'Average of Jul-18', 'Average of Aug-18', 'Average of Sep-18',
    'Average of Oct-18', 'Average of Nov-18', 'Average of Dec-18'
]

# Replace only the null values in the specified columns with the mean of each column
for column in columns_to_fill:
    if train[column].isnull().any():  # Check if the column has any null values
        train[column].fillna(train[column].mean(), inplace=True)

In [ ]:
train